function [retrieved_indexes, similarities, new_case] = retrieve(case_library, new_case, similarity_threshold)
    
    weighting_factors = [2 5 2 4 1 3 5 2 5];
    
    max_values = get_max_values(case_library);
    
    retrieved_indexes = [];
    similarities = [];
    
    for i=1:size(case_library,1)
        
        distances = zeros(1,8);
        
        distances(1,1) = calculate_absolute_distance(...
                                case_library{i,'Pregnancies'} / max_values('Pregnancies'), ...
                                new_case.Pregancies / max_values('Pregnancies'));
                            
        distances(1,2) = calculate_absolute_distance(...
                                case_library{i,'Glucose'} / max_values('Glucose'), ...
                                new_case.Glucose / max_values('Glucose'));
        
        distances(1,3) = calculate_absolute_distance( ...
                                case_library{i,'BloodPressure'} / max_values('BloodPressure'), ...
                                new_case.Glucose / max_values('BloodPressure'));
                            
        distances(1,4) = calculate_absolute_distance(...
                                case_library{i,'SkinThickness'} / max_values('SkinThickness'), ...
                                new_case.SkinThickness / max_values('SkinThickness'));
                            
        distances(1,5) = calculate_absolute_distance(...
                                case_library{i,'BloodPressure'} / max_values('BloodPressure'), ...
                                new_case.Glucose / max_values('BloodPressure'));
                            
        distances(1,6) = calculate_absolute_distance(...
                                case_library{i,'BMI'} / max_values('BMI'), ...
                                new_case.BMI / max_values('BMI'));
         
        distances(1,7) = calculate_absolute_distance(...
                                case_library{i,'DiabetesPedigreeFunction'} / max_values('DiabetesPedigreeFunction'), ...
                                new_case.DiabetesPedigreeFunction / max_values('DiabetesPedigreeFunction'));
                            
        distances(1,8) = calculate_absolute_distance(...
                                case_library{i,'Age'} / max_values('Age'), ...
                                new_case.Age / max_values('Age'));
        
        final_similarity = 1 - ((distances * weighting_factors) / sum(weighting_factors));
        %subtrair 1 para converter asemelhan?a em semelhan?a
        
        if final_similarity >= similarity_threshold
            retrieved_indexes = [retrieved_indexes i];
            similarities = [similarities final_similarity];
        end
        
        fprintf('Case %d out of %d has a similarity of %.2f%%...\n', i, size(case_library,1), final_similarity*100);
    end
end

function [max_values] = get_max_values(case_library)

    key_set = {'Pregnancies', ...
        'Glucose', ...
        'BloodPressure', ...
        'SkinThickness', ...
        'Insulin', ...
        'BMI', ...
        'DiabetesPedigreeFunction', ...
        'Age'};
    value_set = {max(case_library{:,'Pregnancies'}), ...
        max(case_library{:,'Glucose'}), ...
        max(case_library{:,'BloodPressure'}),...
        max(case_library{:,'SkinThickness'}),...
        max(case_library{:,'Insulin'}),...
        max(case_library{:,'BMI'}),...
        max(case_library{:,'DiabetesPedigreeFunction'}),...
        max(case_library{:,'Age'}),...
        };
    max_values = containers.Map(key_set, value_set);
end

function [res] = calculate_absolute_distance(val1, val2)

    diff = abs(val1 - val2);
    res = sum(diff)/length(diff);
end

